### PR TITLE
Add ‘Using a form field to assign a role’ section

### PR DESCRIPTION
**Pull request by hilton**

### CODE REVIEW

**Comment by frontendphil** [comment]
@hilton any particular reason why to first create the role, then re-use the form field? You could also just create the form field and then use the role. Seems to be more straight forward .

**Comment by hilton** [comment]
I did it that way because in my example, the normal way to assign to a role is by assigning a task using the built-in task assignee selector, and so using a form field is a customisation.

If it works both ways, then it’s worth adding a note that you can also do it in a different order.

**Comment by frontendphil** [comment]
Alright. Yup, then I would say, we should add that note? Can you do this for the english version?

**Comment by hilton** [comment]
Yes.

**Pull request merged**
