### PR TITLE
#12 Add ‘Forms’ chapter

### PR DESCRIPTION
**Pull request by hilton**

### CODE REVIEW

**Comment by frontendphil** [comment]
@hilton I already used screenshots from the most recent version of the forms. Those include the new form builder and also list fields. WDYT, should we already merge into master because we're gonna release those very soon anyway?

**Comment by hilton** [comment]
I don’t think that’s a good idea, because there’s no need to have the user guide diverge from the current version, and because assumptions like that can easily bite you.

**Comment by frontendphil** [comment]
Alright, then I would say we just let this sit here till and release it alongside E3.

**Comment by hilton** [comment]
I don’t understand. I would have thought that the current text is fine, and that I’ll only need to update the screenshots when E3 is live.

**Comment by frontendphil** [comment]
Yes, the text is fine. However, I told you while you were preparing this chapter that the form builder has changed and I don't see the point in preparing screenshots which I know I will have to change in two weeks time.

**Comment by hilton** [comment]
It’s simply that replacing existing screenshots is far less work than writing the text and creating the chapter structure and markup, so I’ve already done most of the work here. It seems a waste not to release it.

**Pull request merged**
